services:
  - type: web
    name: adlc-emergency-app
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd server && npm install && cd ../client && npm install
    startCommand: npm start
    healthCheckPath: /
    dockerfilePath: ""
    skipCleanup: true
    envVars:
      - key: NODE_ENV
        value: production

